# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-27 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('sku_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('image', models.FileField(upload_to='static/images/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PRODUCT',
            },
        ),
    ]
